env = "localhost"

[mysql]
    [mysql.localhost.test_db]
        dsn = "user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local"

    [mysql.prod.test_db]
        dsn = "user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local"


[grpc]
    [grpc.localhost]

    [grpc.prod]



[redis]
    [redis.localhost]
        addr = "localhost:6379"
        password = ""
        db = 0
        dial_timeout = 5
        read_timeout = 5
        write_timeout = 5
        pool_size = 5

    [redis.prod]
        addr = ""
        password = ""
        db = 0
        dial_timeout = 5
        read_timeout = 5
        write_timeout = 5
        pool_size = 5



[logging]
    level = "debug"
